### ISSUE TITLE
Change the Send Button Text To Icon

### ISSUE THREAD

**Issue by BipulLamsal** [BipulLamsal/PoggersChat#2]
![Screenshot from 2023-08-23 16-32-10](https://github.com/BipulLamsal/PoggersChat/assets/66175991/02a17e4a-1211-407e-9442-0fafd553d9e3)

**Comment by Roshan-Jeniel** [comment]
Hi @BipulLamsal , you can assign this issue to me

**Comment by BipulLamsal** [comment]
hey @Roshan-Jeniel I have assigned you the issue, you can work on it.

**Comment by Roshan-Jeniel** [comment]
@BipulLamsal  Have made the changes , do you want  me to commit to the main branch itself?

![Screenshot](https://github.com/BipulLamsal/PoggersChat/assets/123149937/adcbb16f-976e-4f56-a390-a7390deba9ed)

**Comment by BipulLamsal** [comment]
@Roshan-Jeniel Nice work, Would be nice to create a separate branch

**Comment by Roshan-Jeniel** [comment]
@BipulLamsal Forked and raised PR from my repo , having some issues pushing directly to your repo looking into it

**Comment by BipulLamsal** [comment]
@Roshan-Jeniel Merged the PR
