### ISSUE TITLE
hide input component 

### ISSUE THREAD

**Issue by BipulLamsal** [BipulLamsal/PoggersChat#4]
![image](https://github.com/BipulLamsal/PoggersChat/assets/66175991/a3b5b4c0-5d6e-4cbc-94f0-b9f95bcf2e49)
The login page contains input component which should not be there.
In App.jsx : `{isAuth && <Input></Input>}` fixes the issue.

**Comment by ekkaaditya200** [comment]
Hey I want to try this

**Comment by BipulLamsal** [comment]
@ekkaaditya200 I have assigned you this isssue

**Comment by BipulLamsal** [comment]
nice work!
